# --- H2 in file mode (persists on disk) ---
server.port=8082
<<<<<<< HEAD
spring.datasource.url=jdbc:h2:file:./customerdb;AUTO_SERVER=TRUE
=======
spring.datasource.url=jdbc:h2:file:/Users/ninakandel/customerdb;AUTO_SERVER=TRUE
>>>>>>> 7a1550d4a0a2f0d66d567bb005ba888344454c02
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
